// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.6.1.0
//      SpecFlow Generator Version:1.6.0.0
//      Runtime Version:4.0.30319.235
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
namespace Wrox.BDD.Specs.UAT.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.6.1.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Game Display")]
    public partial class GameDisplayFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "GamePlay.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Game Display", "In order to play the game\r\nAs a player \r\nI should be able to input moves and see\r" +
                    "\nthe state of the game on the console screen", GenerationTargetLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Starting a game")]
        public virtual void StartingAGame()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Starting a game", ((string[])(null)));
#line 7
this.ScenarioSetup(scenarioInfo);
#line 8
 testRunner.Given("that I have started a new game");
#line hidden
#line 9
    testRunner.Then("I should see the following displayed:", "=========================\r\nLets Play Tic-Tac-Toe!!!!\r\n=========================\r\n" +
                    "When prompted please input the\r\ncoordinates of your move in the\r\nformat row,col " +
                    "e.g. 0,1 for the\r\nfirst row and the second column\r\n\r\nX, make your move.\r\n\r\n", ((TechTalk.SpecFlow.Table)(null)));
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Alternate Players")]
        public virtual void AlternatePlayers()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Alternate Players", ((string[])(null)));
#line 24
this.ScenarioSetup(scenarioInfo);
#line 25
 testRunner.Given("that I have started a new game");
#line 26
 testRunner.And("I have read the introduction message");
#line 27
 testRunner.When("a player types in the coordinates \"2,2\"");
#line hidden
#line 28
    testRunner.Then("I should see the following displayed:", "   |   |   \r\n-----------\r\n   |   |   \r\n-----------\r\n   |   | X \r\n\r\nO, make your m" +
                    "ove.\r\n\r\n", ((TechTalk.SpecFlow.Table)(null)));
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Displaying the game")]
        public virtual void DisplayingTheGame()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Displaying the game", ((string[])(null)));
#line 41
this.ScenarioSetup(scenarioInfo);
#line 42
 testRunner.Given("that I have started a new game");
#line 43
 testRunner.And("I have read the introduction message");
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "player",
                        "row",
                        "column"});
            table1.AddRow(new string[] {
                        "X",
                        "1",
                        "1"});
            table1.AddRow(new string[] {
                        "O",
                        "0",
                        "1"});
#line 44
    testRunner.And("the following moves are played:", ((string)(null)), table1);
#line 48
 testRunner.When("a player types in the coordinates \"2,2\"");
#line hidden
#line 49
    testRunner.Then("I should see the following displayed:", "   | O |   \r\n-----------\r\n   | X |   \r\n-----------\r\n   |   | X \r\n\r\nO, make your m" +
                    "ove.\r\n\r\n", ((TechTalk.SpecFlow.Table)(null)));
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Placing a token in an occupied square")]
        public virtual void PlacingATokenInAnOccupiedSquare()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Placing a token in an occupied square", ((string[])(null)));
#line 62
this.ScenarioSetup(scenarioInfo);
#line 63
 testRunner.Given("that I have started a new game");
#line 64
 testRunner.And("I have read the introduction message");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "player",
                        "row",
                        "column"});
            table2.AddRow(new string[] {
                        "X",
                        "1",
                        "1"});
#line 65
 testRunner.And("the following moves are played:", ((string)(null)), table2);
#line 68
 testRunner.When("a player types in the coordinates \"1,1\"");
#line hidden
#line 69
    testRunner.Then("I should see the following displayed:", "There is already a token in the square at coordinate 1,1.\r\n\r\n   |   |   \r\n-------" +
                    "----\r\n   | X |   \r\n-----------\r\n   |   |   \r\n\r\nO, make your move.\r\n\r\n", ((TechTalk.SpecFlow.Table)(null)));
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Placing a token in an invalid square")]
        public virtual void PlacingATokenInAnInvalidSquare()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Placing a token in an invalid square", ((string[])(null)));
#line 84
this.ScenarioSetup(scenarioInfo);
#line 85
 testRunner.Given("that I have started a new game");
#line 86
 testRunner.And("I have read the introduction message");
#line 87
 testRunner.When("a player types in the coordinates \"100,100\"");
#line hidden
#line 88
    testRunner.Then("I should see the following displayed:", "There is not a square at coordinate 100,100.\r\n\r\n   |   |   \r\n-----------\r\n   |   " +
                    "|   \r\n-----------\r\n   |   |   \r\n\r\nX, make your move.\r\n\r\n", ((TechTalk.SpecFlow.Table)(null)));
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Inputting invalid data")]
        public virtual void InputtingInvalidData()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Inputting invalid data", ((string[])(null)));
#line 103
this.ScenarioSetup(scenarioInfo);
#line 104
 testRunner.Given("that I have started a new game");
#line 105
 testRunner.And("I have read the introduction message");
#line 106
 testRunner.When("a player types in the coordinates \"rrr,fff\"");
#line hidden
#line 107
    testRunner.Then("I should see the following displayed:", "rrr,fff are invalid coordinates for a move, please use the format col,row.\r\n\r\n   " +
                    "|   |   \r\n-----------\r\n   |   |   \r\n-----------\r\n   |   |   \r\n\r\nX, make your mov" +
                    "e.\r\n\r\n", ((TechTalk.SpecFlow.Table)(null)));
#line hidden
            testRunner.CollectScenarioErrors();
        }
    }
}
#endregion
