// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.6.1.0
//      SpecFlow Generator Version:1.6.0.0
//      Runtime Version:4.0.30319.235
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
namespace Wrox.BDD.Specs.UAT.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.6.1.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Win A Game")]
    public partial class WinAGameFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "PlayerWinsAGame.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Win A Game", "  In order to win a game of Tic-Tac-Toe\r\n  As player \r\n  I must get 3 of my token" +
                    "s in a row", GenerationTargetLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Diagonal Win Left to Right Token X")]
        public virtual void DiagonalWinLeftToRightTokenX()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Diagonal Win Left to Right Token X", ((string[])(null)));
#line 6
this.ScenarioSetup(scenarioInfo);
#line 7
    testRunner.Given("that I have started a new game");
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "player",
                        "row",
                        "column"});
            table1.AddRow(new string[] {
                        "X",
                        "1",
                        "1"});
            table1.AddRow(new string[] {
                        "O",
                        "0",
                        "2"});
            table1.AddRow(new string[] {
                        "X",
                        "0",
                        "0"});
            table1.AddRow(new string[] {
                        "O",
                        "1",
                        "2"});
#line 8
 testRunner.And("the following moves are played:", ((string)(null)), table1);
#line 14
    testRunner.When("a player types in the coordinates \"2,2\"");
#line hidden
#line 15
 testRunner.Then("I should see the following displayed:", " X |   | O \r\n-----------\r\n   | X | O \r\n-----------\r\n   |   | X \r\n\r\nX has won the " +
                    "game!\r\n", ((TechTalk.SpecFlow.Table)(null)));
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Diagonal Win Left to Right Token O")]
        public virtual void DiagonalWinLeftToRightTokenO()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Diagonal Win Left to Right Token O", ((string[])(null)));
#line 27
this.ScenarioSetup(scenarioInfo);
#line 28
    testRunner.Given("that I have started a new game");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "player",
                        "row",
                        "column"});
            table2.AddRow(new string[] {
                        "X",
                        "0",
                        "2"});
            table2.AddRow(new string[] {
                        "O",
                        "1",
                        "1"});
            table2.AddRow(new string[] {
                        "X",
                        "1",
                        "2"});
            table2.AddRow(new string[] {
                        "O",
                        "0",
                        "0"});
            table2.AddRow(new string[] {
                        "X",
                        "2",
                        "0"});
#line 29
 testRunner.And("the following moves are played:", ((string)(null)), table2);
#line 36
    testRunner.When("a player types in the coordinates \"2,2\"");
#line hidden
#line 37
 testRunner.Then("I should see the following displayed:", " O |   | X \r\n-----------\r\n   | O | X \r\n-----------\r\n X |   | O \r\n\r\nO has won the " +
                    "game!\r\n", ((TechTalk.SpecFlow.Table)(null)));
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Alternative Diagonal Win Right to Left Token X")]
        public virtual void AlternativeDiagonalWinRightToLeftTokenX()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Alternative Diagonal Win Right to Left Token X", ((string[])(null)));
#line 49
this.ScenarioSetup(scenarioInfo);
#line 50
    testRunner.Given("that I have started a new game");
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "player",
                        "row",
                        "column"});
            table3.AddRow(new string[] {
                        "X",
                        "1",
                        "1"});
            table3.AddRow(new string[] {
                        "O",
                        "1",
                        "2"});
            table3.AddRow(new string[] {
                        "X",
                        "0",
                        "2"});
            table3.AddRow(new string[] {
                        "O",
                        "2",
                        "2"});
#line 51
 testRunner.And("the following moves are played:", ((string)(null)), table3);
#line 57
    testRunner.When("a player types in the coordinates \"2,0\"");
#line hidden
#line 58
 testRunner.Then("I should see the following displayed:", "   |   | X \r\n-----------\r\n   | X | O \r\n-----------\r\n X |   | O \r\n\r\nX has won the " +
                    "game!\r\n", ((TechTalk.SpecFlow.Table)(null)));
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Alternative Diagonal Win Right to Left Token O")]
        public virtual void AlternativeDiagonalWinRightToLeftTokenO()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Alternative Diagonal Win Right to Left Token O", ((string[])(null)));
#line 70
this.ScenarioSetup(scenarioInfo);
#line 71
    testRunner.Given("that I have started a new game");
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "player",
                        "row",
                        "column"});
            table4.AddRow(new string[] {
                        "X",
                        "1",
                        "2"});
            table4.AddRow(new string[] {
                        "O",
                        "1",
                        "1"});
            table4.AddRow(new string[] {
                        "X",
                        "2",
                        "2"});
            table4.AddRow(new string[] {
                        "O",
                        "0",
                        "2"});
            table4.AddRow(new string[] {
                        "X",
                        "2",
                        "1"});
#line 72
 testRunner.And("the following moves are played:", ((string)(null)), table4);
#line 79
    testRunner.When("a player types in the coordinates \"2,0\"");
#line hidden
#line 80
 testRunner.Then("I should see the following displayed:", "   |   | O \r\n-----------\r\n   | O | X \r\n-----------\r\n O | X | X \r\n\r\nO has won the " +
                    "game!\r\n", ((TechTalk.SpecFlow.Table)(null)));
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Vertical Win")]
        public virtual void VerticalWin()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Vertical Win", ((string[])(null)));
#line 91
this.ScenarioSetup(scenarioInfo);
#line 92
    testRunner.Given("that I have started a new game");
#line hidden
            TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                        "player",
                        "row",
                        "column"});
            table5.AddRow(new string[] {
                        "X",
                        "1",
                        "1"});
            table5.AddRow(new string[] {
                        "O",
                        "0",
                        "2"});
            table5.AddRow(new string[] {
                        "X",
                        "0",
                        "1"});
            table5.AddRow(new string[] {
                        "O",
                        "1",
                        "2"});
#line 93
 testRunner.And("the following moves are played:", ((string)(null)), table5);
#line 99
    testRunner.When("a player types in the coordinates \"2,1\"");
#line hidden
#line 100
 testRunner.Then("I should see the following displayed:", "X has won the game!\r\n\r\n   | X | O \r\n-----------\r\n   | X | O \r\n-----------\r\n   | X" +
                    " |   \r\n\r\n", ((TechTalk.SpecFlow.Table)(null)));
#line hidden
            testRunner.CollectScenarioErrors();
        }
    }
}
#endregion
